context:
  version: "0.14.0"
  python_min: '3.10'

package:
  name: orcestra-downloader
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/orcestra-downloader/orcestra_downloader-${{ version }}.tar.gz
    sha256: 428a43302d4a0684dc287c0ce48fbe77c792ab8789f47666b6e163ab995a8387

build:
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - orcestra = orcestradownloader.cli.cli:cli
      - orcestra-downloader = orcestradownloader.cli.cli:cli
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - aiohttp >=3.11.4
    - click >=8.1.7
    - 'rich '

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - orcestradownloader
      pip_check: true

about:
  summary: Simplified access to download data from orcestra.ca
  license: MIT
  license_file: LICENSE
  homepage: "https://github.com/bhklab/orcestra-downloader"
  repository: "https://github.com/bhklab/orcestra-downloader"
  documentation: "https://bhklab.github.io/orcestra-downloader/"

extra:
  recipe-maintainers:
    - jjjermiah
